services:
  mongodb:
    image: mongo:7.0
    container_name: assessment_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: assessment_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  app:
    build: .
    container_name: employee_management_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://mongodb:27017
      PYTHONPATH: /app
      SECRET_KEY: your-super-secret-jwt-key-change-this-in-production-12345
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - mongodb
    networks:
      - app_network
    volumes:
      - .:/app
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
